#demo_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: DemoBundle:Default:index }
    
articulos:
    pattern: /articulos
    defaults: { _controller: DemoBundle:Default:articulos }
    
articulo:
    pattern: /articulo/{id}
    defaults: { _controller: DemoBundle:Default:articulo }

path_hello_world:
    pattern: /hello
    defaults: { _controller: DemoBundle:Default:index }
    
blog_mostrar:
    pattern: /blog/{slug}
    defaults: { _controller: DemoBundle:Blog:show }
    
blog_index:
    pattern: /blog/page/{page}
    defaults: { _controller: DemoBundle:Blog:index, page: 1 }