#demo_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: DemoBundle:Default:index }
    
articulos:
    pattern: /articulos
    defaults: { _controller: DemoBundle:Default:articulos }
      
articulos_listar:
    pattern: /articulos/listar
    defaults: { _controller: DemoBundle:Articulos:listar }
    
articulo:
    pattern: /articulo/{id}
    defaults: { _controller: DemoBundle:Default:articulo }
    requirements:
        id: \d+

articulo_crear:
    pattern: /articulo/crear
    defaults: { _controller: DemoBundle:Articulos:crear }
    
articulo_editar:
    pattern: /articulo/editar
    defaults: { _controller: DemoBundle:Articulos:editar }
    
articulo_visualizar:
    pattern: /articulo/visualizar/{id}
    defaults: { _controller: DemoBundle:Articulos:visualizar }
    
articulo_borrar:
    pattern: /articulo/borrar/{id}
    defaults: { _controller: DemoBundle:Articulos:borrar }
    
articulo_new:
    pattern: /articulo/new
    defaults: { _controller: DemoBundle:Articulos:new }
    
path_hello_world:
    pattern: /hello
    defaults: { _controller: DemoBundle:Default:index }
    
blog_index:
    pattern: /blog/{page}
    defaults: { _controller: DemoBundle:Blog:index, page: 1 }
    requirements:
        page: \d+

blog_mostrar:
    pattern: /blog/{slug}
    defaults: { _controller: DemoBundle:Blog:show }
    
blog_articulos:
    pattern: /articulos/{culture}/{year}/{titulo}.{_format}
    defaults: { _controller: DemoBundle:Blog:articulos, _format: html}
    requirements:
        culture: en|es
        _format: html|rss
        year: \d{4}+
        
ver_articulos:
    pattern: /ver-articulos
    defaults: { _controller: DemoBundle:Articulos:verArticulos }
    
DemoBundle_noticias:
    pattern: /noticias
    defaults: { _controller: DemoBundle:Notice:index }
    
DemoBundle_noticeView:
    pattern: /leerNoticia/{notice_id}
    defaults: { _controller: DemoBundle:Notice:noticeView }