security:
    encoders:
        Rogama\DemoBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    providers:
        user_db:
            entity: { class: Rogama\DemoBundle\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/admin/login$
            security: false
        secured_area:
            pattern: ^/admin/
#            http_basic:
#                realm: "Introduzca usuario y contraseña"
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path: /admin/logout
                target: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
                